"""MQSim simulation output parser.

Parses MQSim's output XML (workload_scenario_N.xml) to extract
performance metrics.  The XML is generated by mqsim_pybind.cpp's
write_results() and has a flat structure under <Host.IO_Flow>.
"""

import os
import xml.etree.ElementTree as ET
from dataclasses import dataclass


@dataclass
class MQSimResult:
    """Structured output from a single MQSim simulation run.

    All latency values are in nanoseconds.  Bandwidth in bytes/second.
    IOPS in operations/second.
    """

    # request counts
    total_read_requests: int = 0
    total_write_requests: int = 0

    # bytes transferred
    total_bytes_read: int = 0
    total_bytes_written: int = 0

    # performance
    bandwidth_bytes_per_sec: float = 0.0
    iops_read: float = 0.0
    iops_write: float = 0.0

    # latency  (from MQSim's Device_Response_Time / End_to_End_Request_Delay)
    device_response_time_us: float = 0.0
    end_to_end_delay_us: float = 0.0

    # derived
    total_time_s: float = 0.0

    # ---- derived properties ----

    @property
    def total_requests(self) -> int:
        return self.total_read_requests + self.total_write_requests

    @property
    def total_bytes(self) -> int:
        return self.total_bytes_read + self.total_bytes_written

    @property
    def total_iops(self) -> float:
        return self.iops_read + self.iops_write

    @property
    def avg_latency_us(self) -> float:
        return self.device_response_time_us


# ---------------------------------------------------------------------------
# Tag → (field, converter) mapping for <Host.IO_Flow> children
# ---------------------------------------------------------------------------

_TAG_MAP = {
    "Read_Request_Count":       ("total_read_requests",  int),
    "Write_Request_Count":      ("total_write_requests", int),
    "Bytes_Transferred_Read":   ("total_bytes_read",     int),
    "Bytes_Transferred_Write":  ("total_bytes_written",  int),
    "Bandwidth":                ("bandwidth_bytes_per_sec", float),
    "IOPS_Read":                ("iops_read",            float),
    "IOPS_Write":               ("iops_write",           float),
    "Device_Response_Time":     ("device_response_time_us", float),
    "End_to_End_Request_Delay": ("end_to_end_delay_us",   float),
}


def parse_mqsim_output(xml_path: str) -> MQSimResult:
    """Parse an MQSim workload_scenario_N.xml output file.

    Args:
        xml_path: Path to MQSim output XML.

    Returns:
        MQSimResult with extracted performance metrics.

    Raises:
        FileNotFoundError: If the output file does not exist.
    """
    if not os.path.isfile(xml_path):
        raise FileNotFoundError(f"MQSim output file not found: {xml_path}")

    root = ET.parse(xml_path).getroot()
    result = MQSimResult()

    flow = root.find(".//Host.IO_Flow")
    if flow is None:
        return result

    for child in flow:
        tag = child.tag
        if tag not in _TAG_MAP:
            continue
        text = (child.text or "").strip()
        if not text:
            continue

        field, conv = _TAG_MAP[tag]
        try:
            val = conv(float(text)) if conv is int else conv(text)
        except (ValueError, TypeError):
            continue
        setattr(result, field, val)

    # compute total_time_s from bytes / bandwidth
    if result.bandwidth_bytes_per_sec > 0:
        total = result.total_bytes
        if total > 0:
            result.total_time_s = (
                total / result.bandwidth_bytes_per_sec
            )

    return result
